### ISSUE TITLE
Cookie not returned from the browser

### ISSUE THREAD

**Issue by tchap** [gorilla/securecookie#40] opened 2016-06-14 11:24 UTC
Hello,

I am having issues using `securecookie`. When I encode a value and send it to the browser, it is sometimes not returning it back. Seems to me like the browser doesn't like some of the characters in the encoded cookie value. I am using Google Chrome, up to date.

Tried replacing `base64` with `base32.StdEncoding` in this package and also replacing the padding `=` with `0`, which is ok for `base32.StdEncoding`, and it all started working.

So, I am basically asking where the issues is. How come this package is working for other people?

In case I don't want to fork this package, what am I supposed to do? Encode the value returned from `securecookie` with `base32`? That will only increase the cookie size, although it is not really dramatic for my use case...

Thanks!

**Comment by elithrar** [comment] 2016-06-14 13:00
Do you have a minimal reproducible example? There is no reason for base64
encoded values to have issues.

**Comment by tchap** [comment] 2016-06-14 13:16
I will try to extract it when I have time, but basically I started looking into it when I discovered that sometimes the cookie is returned and sometimes it is not, i.e. sometimes I am successfully logged into my app, sometimes it redirects me back to the login page even though on the server the profile object is always successfully assembled...

**Comment by elithrar** [comment] 2016-06-14 13:53
Can you show me the cookie from Chrome's Web Inspector?

e.g. Resources -> Cookies -> screenshot that window when logged into your
app.

**Comment by elithrar** [comment] 2016-06-15 13:53
Just to build on what I said above: the issue is likely with the "Path" object. If you set the cookie at (e.g.) `/login` but users visit `/` or `/dashboard`, the cookie will not be 'in scope' and the browser will not send it in the request.

**Comment by tchap** [comment] 2016-06-15 13:56
I don't think that is the issue because really my login implementation works for Facebook and GitHub, but it fails with one of my Google accounts and not with the other one, so it must be something weird with the cookie value generated. I don't have time to look into this right now, but I will try to get back and generate a cookie that is not working.

**Comment by elithrar** [comment] 2016-07-23 03:48
Closing this for now, but please re-open if you still need help.

**Closed** 2016-10-10 13:00 UTC
Labels: question
